<?php
/**
 * Present "more" links either as buttons or text links with icons.
 */

use Drupal\custom_more\CustomMoreManager;

/**
 * Implements hook_theme().
 */
function custom_more_theme() {
  $items = [
    'more_icon_link' => [
      'render element' => 'element',
    ],
  ];
  return $items;
}

/**
 * Implements hook_preprocess_links().
 */
function custom_more_preprocess_links(&$variables) {
  if (isset($variables['links']['node-readmore'])) {
    $type = CustomMoreManager::moreType();
    $icon = CustomMoreManager::icon();
    $title = $variables['links']['node-readmore']['link']['#title'];
    $new_text = CustomMoreManager::appendIcon($title, $icon, 'after');
    $variables['links']['node-readmore']['link']['#title'] = $new_text;
    $variables['links']['node-readmore']['#attached'] = CustomMoreManager::library();

    switch ($type) {
      case 'button':
      $classes = CustomMoreManager::buttonClasses();
    $variables['links']['node-readmore']['link']['#options']['attributes']['class'] = $classes;
        break;
      case 'link':
        break;
    }
  }
}

/**
 * Implements hook_preprocess_views_view()
  */
function custom_more_preprocess_views_view(&$variables) {
  if (array_key_exists('more', $variables)) {
    // Replace the Views 'more_link' element with our more_icon_link element.
    $type = CustomMoreManager::moreType();
    $variables['more']['#type'] = 'more_icon_link';
    $variables['more']['#icon'] = CustomMoreManager::icon();
    $variables['more']['#icon_position'] = 'after';
    $variables['more']['#attached'] =  CustomMoreManager::library();
    switch ($type) {
      case 'button':
        $classes = CustomMoreManager::buttonClasses();
        $variables['more']['#attributes']['class'] = $classes;
        break;
      case 'link':
        break;
     }
  }
}

